## Importing the libraries

In [144]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [145]:
path = "your dataset's path"
df = pd.read_csv(path)
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890     0.0  
1          0.2750                  0.08902     0.0  
2          0.3613                  0.08758     0.0  
3          0.6638                  0.17300     0.0  
4          0.2364                  0.07678     0.0  

[5 rows x 31 columns]

## Check Missing Data

In [146]:
missing_data = df.isnull()
missing_data.head()

for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")
    
#no Missing data

mean radius
False    569
Name: mean radius, dtype: int64

mean texture
False    569
Name: mean texture, dtype: int64

mean perimeter
False    569
Name: mean perimeter, dtype: int64

mean area
False    569
Name: mean area, dtype: int64

mean smoothness
False    569
Name: mean smoothness, dtype: int64

mean compactness
False    569
Name: mean compactness, dtype: int64

mean concavity
False    569
Name: mean concavity, dtype: int64

mean concave points
False    569
Name: mean concave points, dtype: int64

mean symmetry
False    569
Name: mean symmetry, dtype: int64

mean fractal dimension
False    569
Name: mean fractal dimension, dtype: int64

radius error
False    569
Name: radius error, dtype: int64

texture error
False    569
Name: texture error, dtype: int64

perimeter error
False    569
Name: perimeter error, dtype: int64

area error
False    569
Name: area error, dtype: int64

smoothness error
False    569
Name: smoothness error, dtype: int64

compactness error
False    569
Name: c

## Checking the correlation

In [147]:
corr = df.corr()
corr = corr["target"]
corr

mean radius               -0.730029
mean texture              -0.415185
mean perimeter            -0.742636
mean area                 -0.708984
mean smoothness           -0.358560
mean compactness          -0.596534
mean concavity            -0.696360
mean concave points       -0.776614
mean symmetry             -0.330499
mean fractal dimension     0.012838
radius error              -0.567134
texture error              0.008303
perimeter error           -0.556141
area error                -0.548236
smoothness error           0.067016
compactness error         -0.292999
concavity error           -0.253730
concave points error      -0.408042
symmetry error             0.006522
fractal dimension error   -0.077972
worst radius              -0.776454
worst texture             -0.456903
worst perimeter           -0.782914
worst area                -0.733825
worst smoothness          -0.421465
worst compactness         -0.590998
worst concavity           -0.659610
worst concave points      -0

## Dropp low correlation columns

In [148]:
dataset = df.drop(['mean fractal dimension' , 'texture error' , 'smoothness error' , 'symmetry error' , 'fractal dimension error'] , axis=1)
dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   radius error  ...  worst texture  worst perimeter  worst area  \
0        1.0950  ...          17.33           184.60      2019.0   
1        0.5435  ...          23.41           158.80      1956.0   
2        0.7456  ...          25.53           152.50      1709.0   
3        0.4956  ...          26.50            98.87       567.7   
4        0.7572  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890     0.0  
1          0.2750                  0.08902     0.0  
2          0.3613                  0.08758     0.0  
3          0.6638                  0.17300     0.0  
4          0.2364                  0.07678     0.0  

[5 rows x 26 columns]

## 1's VS 0's

In [149]:
dataset['target'].value_counts()

1.0    357
0.0    212
Name: target, dtype: int64

## Splitting input & output

In [150]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [151]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [152]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [153]:
print(X_train)

[[-1.15 -0.39 -1.13 ... -0.76 -0.02 -0.39]
 [-0.94  0.68 -0.95 ... -0.61  0.1  -0.39]
 [ 0.57 -1.03  0.51 ... -0.02 -0.2  -0.75]
 ...
 [-1.32 -0.2  -1.32 ... -0.98 -0.72 -0.12]
 [-1.24 -0.22 -1.28 ... -1.75 -1.58 -1.01]
 [-0.74  1.15 -0.71 ... -0.27 -1.26  0.22]]


In [154]:
print(X_test)

[[-0.2   0.33 -0.13 ...  1.39  1.08  1.54]
 [-0.26  1.47 -0.32 ... -0.83 -0.73 -0.88]
 [-0.03 -0.84 -0.09 ... -0.49 -1.22 -0.92]
 ...
 [ 1.72  0.09  1.73 ...  1.58  0.2  -0.15]
 [ 1.19  0.34  1.19 ...  0.56  0.27 -0.27]
 [ 0.26 -0.58  0.28 ... -0.19 -1.16  0.11]]


## Training the model

In [155]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 1)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

## Predicting the Test set results and comparing them

In [156]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 

## Confusion matrix

In [157]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[45  2]
 [ 1 66]]


0.9736842105263158